POST {{host}}/client
Authorization: Basic {{username}} {{password}}
Accept: application/json
x-dw-client-id: SFCCDebugger
###

DELETE {{host}}/client
Authorization: Basic {{username}} {{password}}
Accept: application/json
x-dw-client-id: SFCCDebugger
###

GET {{host}}/breakpoints
Authorization: Basic {{username}} {{password}}
Accept: application/json
x-dw-client-id: SFCCDebugger
###

GET {{host}}/threads
Authorization: Basic {{username}} {{password}}
Accept: application/json
x-dw-client-id: SFCCDebugger
###

POST {{host}}/threads/reset
Authorization: Basic {{username}} {{password}}
Accept: application/json
x-dw-client-id: SFCCDebugger
